import { notFound } from "next/navigation";
import { addAuthorAction, removeAuthorAction, submitSubmissionAction, updateSubmissionAction, uploadSubmissionVersionAction, withdrawSubmissionAction } from "@/app/actions/submissions";
import { ActionForm } from "@/components/workspace/action-form";
import { requireAccount } from "@/lib/auth";
import { db } from "@/lib/db";
import { canEditSubmission } from "@/lib/submission-policy";
import { formatDate } from "@/lib/text";

export default async function SubmissionPage({ params }: { params: Promise<{ id: string }> }) {
  const user = await requireAccount(); const { id } = await params;
  const item = await db.submission.findFirst({ where: { id, ownerId: user.id }, include: { conference: { include: { tracks: true } }, authors: { orderBy: { sortOrder: "asc" } }, versions: { include: { media: true }, orderBy: { versionNumber: "desc" } }, decisions: { orderBy: { createdAt: "desc" } }, assignments: { where: { status: "COMPLETED" }, include: { review: true } } } });
  if (!item) notFound(); const editable = canEditSubmission(item.status);
  const update = updateSubmissionAction.bind(null, item.id); const addAuthor = addAuthorAction.bind(null, item.id); const upload = uploadSubmissionVersionAction.bind(null, item.id);
  return <><header className="admin-header"><div><p className="eyebrow">{item.conference.title}</p><h1>{item.title}</h1><span className="badge">{item.status.replaceAll("_", " ")}</span></div></header>
    {editable ? <ActionForm action={update} submitLabel="Save draft"><fieldset><legend>Submission details</legend><input type="hidden" name="conferenceId" value={item.conferenceId}/><label className="wide">Title<input name="title" defaultValue={item.title} required/></label><label>Type<select name="kind" defaultValue={item.kind}><option value="ABSTRACT">Abstract</option><option value="FULL_PAPER">Full paper</option><option value="POSTER">Poster</option><option value="WORKSHOP_PROPOSAL">Workshop proposal</option></select></label><label>Track<select name="trackId" defaultValue={item.trackId || ""}><option value="">No track</option>{item.conference.tracks.map(t => <option value={t.id} key={t.id}>{t.title}</option>)}</select></label><label className="wide">Abstract or summary<textarea name="abstractText" defaultValue={item.abstractText} minLength={50} rows={10} required/></label><label className="wide">Keywords<input name="keywords" defaultValue={item.keywords || ""}/></label></fieldset></ActionForm> : <section className="admin-panel"><h2>Abstract or summary</h2><p className="prose">{item.abstractText}</p>{item.keywords && <p><strong>Keywords:</strong> {item.keywords}</p>}</section>}
    <section className="admin-panel"><h2>Authors</h2><div className="responsive-table"><table><thead><tr><th>Name</th><th>Affiliation</th><th>Role</th>{editable && <th>Action</th>}</tr></thead><tbody>{item.authors.map(a => <tr key={a.id}><td>{a.name}<small>{a.email}</small></td><td>{a.affiliation || "—"}{a.country && <small>{a.country}</small>}</td><td>{a.corresponding ? "Corresponding author" : "Co-author"}</td>{editable && <td>{!a.corresponding && <form action={removeAuthorAction.bind(null, item.id, a.id)}><button className="danger">Remove</button></form>}</td>}</tr>)}</tbody></table></div>{editable && <ActionForm action={addAuthor} submitLabel="Add author" className="inline-form"><label>Name<input name="name" required/></label><label>Email<input name="email" type="email" required/></label><label>Affiliation<input name="affiliation"/></label><label>Country<input name="country"/></label><label><span><input name="corresponding" type="checkbox"/> Corresponding</span></label></ActionForm>}</section>
    <section className="admin-panel"><h2>Manuscript versions</h2>{item.versions.length ? <ul>{item.versions.map(v => <li key={v.id}><a href={`/media/${v.mediaId}`}>Version {v.versionNumber}: {v.media?.originalName}</a> — {formatDate(v.submittedAt)}{v.responseToReviewers && <p><strong>Response to reviewers:</strong> {v.responseToReviewers}</p>}</li>)}</ul> : <p>No PDF has been uploaded. Abstract-only submissions do not require one.</p>}{editable && <ActionForm action={upload} submitLabel="Upload new version"><label>PDF file<input name="file" type="file" accept="application/pdf,.pdf" required/></label>{item.status === "REVISION_REQUESTED" && <label>Response to reviewers<textarea name="responseToReviewers" rows={6} required/></label>}</ActionForm>}</section>
    {item.assignments.some(a => a.review) && <section className="admin-panel"><h2>Reviewer feedback</h2>{item.assignments.map((a, index) => a.review && <article key={a.id}><h3>Review {index + 1}: {a.review.recommendation.replaceAll("_", " ")}</h3><p className="prose">{a.review.authorComments}</p></article>)}</section>}
    {item.decisions.length > 0 && <section className="admin-panel"><h2>Editorial decisions</h2>{item.decisions.map(d => <article key={d.id}><h3>{d.type.replaceAll("_", " ")}</h3><p className="prose">{d.comments}</p><small>{formatDate(d.createdAt)}</small></article>)}</section>}
    <section className="admin-panel"><div className="action-row">{editable && <form action={submitSubmissionAction.bind(null, item.id)}><button className="primary">{item.status === "REVISION_REQUESTED" ? "Submit revision" : "Submit for review"}</button></form>}{["SUBMITTED", "UNDER_REVIEW", "REVISION_REQUESTED"].includes(item.status) && <form action={withdrawSubmissionAction.bind(null, item.id)}><button className="danger">Withdraw submission</button></form>}</div></section></>;
}
