import { notFound } from "next/navigation";
import { db } from "@/lib/db";
import { ConferenceForm } from "@/components/admin/conference-form";
import { LifecycleButtons } from "@/components/admin/lifecycle-buttons";
import { updateConferenceAction, addTrackAction, addSpeakerAction, addCommitteeAction, addCommitteeMemberAction, addFeeAction, addProgrammeItemAction, addSponsorAction, addFaqAction, addAnnouncementAction, toggleSectionAction } from "@/app/actions/conferences";
import { assignConferenceMediaAction } from "@/app/actions/media";

const Field = ({ name, placeholder, type="text", required=false }: { name:string; placeholder:string; type?:string; required?:boolean }) => <input name={name} placeholder={placeholder} type={type} required={required}/>;
export default async function EditConference({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const c = await db.conference.findUnique({ where: { id }, include: { sections: { orderBy: { sortOrder: "asc" } }, importantDates: { orderBy: { date: "asc" } }, tracks: true, speakers: true, committees: { include: { members: true } }, fees: true, programmeItems: true, sponsors: true, faqs: true, announcements: true, media: true, documents: { include: { media: true } } } });
  if (!c) notFound();
  const update = updateConferenceAction.bind(null, c.id);
  return <><header className="admin-header"><div><p className="eyebrow">Conference builder · {c.status}</p><h1>{c.title}</h1><p>Changes remain server validated. Publication controls do not delete the record.</p></div><LifecycleButtons id={c.id} status={c.status}/></header>
    <details open className="builder-section"><summary>Core conference information</summary><ConferenceForm conference={c} action={update}/></details>
    <details className="builder-section"><summary>Branding and documents</summary><p>Upload assets through the Media library, then assign a conference-associated asset below.</p><a className="button" href={`/admin/media?conferenceId=${c.id}`}>Open Media library</a>{c.media.length ? <form className="inline-form" action={assignConferenceMediaAction.bind(null,c.id)}><select name="assetId">{c.media.map(a=><option key={a.id} value={a.id}>{a.originalName}</option>)}</select><select name="role"><option>LOGO</option><option>BANNER</option><option>SOCIAL</option><option>DOCUMENT</option></select><Field name="title" placeholder="Document title"/><Field name="documentType" placeholder="Brochure / programme / other"/><button>Assign asset</button></form> : <p>No conference media has been uploaded.</p>}{c.documents.map(d=><p key={d.id}>{d.title} · {d.documentType}</p>)}</details>
    <details className="builder-section"><summary>Microsite sections</summary><div className="section-config">{c.sections.map(s=><form action={async (fd)=>{"use server"; await toggleSectionAction(c.id,s.id,fd.get("enabled")==="on",fd.get("showWhenEmpty")==="on");}} key={s.id}><strong>{s.label}</strong><label><input type="checkbox" name="enabled" defaultChecked={s.enabled}/> Enabled</label><label><input type="checkbox" name="showWhenEmpty" defaultChecked={s.showWhenEmpty}/> Show truthful empty state</label><button>Save</button></form>)}</div></details>
    <details className="builder-section"><summary>Important dates ({c.importantDates.length})</summary><form className="inline-form" action={async(fd)=>{"use server"; const { addImportantDateAction }=await import("@/app/actions/conferences"); await addImportantDateAction(c.id,{ok:false,message:""},fd);}}><select name="type">{["ABSTRACT_OPENS","ABSTRACT_DEADLINE","FULL_PAPER_DEADLINE","NOTIFICATION","REVISION_DEADLINE","EARLY_BIRD_DEADLINE","REGULAR_REGISTRATION_DEADLINE","CONFERENCE_START","CONFERENCE_END","CUSTOM"].map(x=><option key={x}>{x}</option>)}</select><Field name="customLabel" placeholder="Custom label"/><Field name="date" placeholder="Date" type="datetime-local" required/><Field name="notes" placeholder="Notes"/><button>Add date</button></form>{c.importantDates.map(d=><p key={d.id}>{d.customLabel || d.type}: {d.date.toLocaleDateString("en")}</p>)}</details>
    <details className="builder-section"><summary>Themes & tracks ({c.tracks.length})</summary><form className="inline-form" action={addTrackAction.bind(null,c.id)}><Field name="title" placeholder="Track title" required/><Field name="description" placeholder="Description"/><button>Add track</button></form>{c.tracks.map(x=><p key={x.id}><strong>{x.title}</strong> {x.description}</p>)}</details>
    <details className="builder-section"><summary>Speakers ({c.speakers.length})</summary><form className="inline-form" action={addSpeakerAction.bind(null,c.id)}><select name="type">{["KEYNOTE","INVITED","PLENARY","GUEST","OTHER"].map(x=><option key={x}>{x}</option>)}</select><Field name="name" placeholder="Name" required/><Field name="designation" placeholder="Designation"/><Field name="affiliation" placeholder="Affiliation"/><Field name="country" placeholder="Country"/><Field name="talkTitle" placeholder="Talk title"/><button>Add speaker</button></form>{c.speakers.map(x=><p key={x.id}><strong>{x.name}</strong> · {x.type} {x.affiliation}</p>)}</details>
    <details className="builder-section"><summary>Committees ({c.committees.length})</summary><form className="inline-form" action={addCommitteeAction.bind(null,c.id)}><Field name="name" placeholder="Committee group" required/><Field name="description" placeholder="Description"/><button>Add committee</button></form>{c.committees.map(group=><section key={group.id}><h3>{group.name}</h3>{group.members.map(m=><p key={m.id}>{m.name} · {m.role} {m.affiliation}</p>)}<form className="inline-form" action={addCommitteeMemberAction.bind(null,c.id,group.id)}><Field name="name" placeholder="Member name" required/><Field name="role" placeholder="Role"/><Field name="affiliation" placeholder="Affiliation"/><Field name="country" placeholder="Country"/><button>Add member</button></form></section>)}</details>
    <details className="builder-section"><summary>Registration fees ({c.fees.length})</summary><form className="inline-form" action={addFeeAction.bind(null,c.id)}><Field name="category" placeholder="Category" required/><Field name="audience" placeholder="Domestic / international"/><Field name="priceTier" placeholder="Early / regular / late" required/><Field name="currency" placeholder="USD" required/><Field name="amount" placeholder="Amount" type="number" required/><Field name="notes" placeholder="Notes"/><button>Add fee</button></form>{c.fees.map(x=><p key={x.id}>{x.category} · {x.priceTier}: {x.currency} {x.amount.toString()}</p>)}</details>
    <details className="builder-section"><summary>Programme ({c.programmeItems.length})</summary><form className="inline-form" action={addProgrammeItemAction.bind(null,c.id)}><Field name="day" placeholder="Day" type="date" required/><Field name="title" placeholder="Session title" required/><Field name="room" placeholder="Room / location"/><Field name="description" placeholder="Description"/><button>Add item</button></form>{c.programmeItems.map(x=><p key={x.id}>{x.day.toLocaleDateString("en")} · {x.title} {x.room}</p>)}</details>
    <details className="builder-section"><summary>Sponsors / supporters ({c.sponsors.length})</summary><form className="inline-form" action={addSponsorAction.bind(null,c.id)}><Field name="name" placeholder="Organization name" required/><Field name="tier" placeholder="Tier / category"/><Field name="url" placeholder="Website URL" type="url"/><button>Add sponsor</button></form>{c.sponsors.map(x=><p key={x.id}>{x.name} · {x.tier}</p>)}</details>
    <details className="builder-section"><summary>Conference FAQ ({c.faqs.length})</summary><form className="inline-form" action={addFaqAction.bind(null,c.id)}><Field name="question" placeholder="Question" required/><Field name="answer" placeholder="Answer" required/><button>Add FAQ</button></form>{c.faqs.map(x=><p key={x.id}><strong>{x.question}</strong><br/>{x.answer}</p>)}</details>
    <details className="builder-section"><summary>Announcements ({c.announcements.length})</summary><form className="inline-form" action={addAnnouncementAction.bind(null,c.id)}><Field name="title" placeholder="Title" required/><Field name="body" placeholder="Announcement" required/><label><input type="checkbox" name="publish"/> Publish now</label><button>Add announcement</button></form></details>
  </>;
}
