import { PageHeader, publicStyles as styles } from "@/components/public/PublicUI";
export const metadata = { title: "About", description: "About the purpose and conference hosting model of ANVA Conferences." };
export default function AboutPage() { return <><PageHeader eyebrow="Our purpose" title="About ANVA Conferences">A multidisciplinary platform for presenting clear, structured information about academic and scientific events.</PageHeader><div className={`${styles.narrow} ${styles.content}`}>
  <h2>A place for scholarly events</h2><p>ANVA Conferences is a scholarly events initiative of ANVA Publishing. It provides a shared digital home for academic and scientific conferences, helping visitors discover events and understand the information supplied by their organizers.</p>
  <h2>Multidisciplinary by design</h2><p>The platform is designed to host events across the sciences, medicine and health, technology, engineering, sustainability, mathematics, interdisciplinary research and other administrator-defined disciplines. Conferences may be international or national and may take place physically, virtually or in a hybrid format.</p>
  <h2>Clear conference information</h2><p>Each published conference can present its purpose, dates, tracks, submission guidance, registration information, speakers, committees, programme, venue, documents and contact details in one structured microsite. Only information entered and published by an authorized administrator is shown.</p>
  <h2>Support for organizers and participants</h2><p>The conference hosting model gives authorized teams a consistent way to maintain event information without changing source code. Participants benefit from searchable, current conference pages and direct access to organizer-supplied guidance. Account, submission, review, payment and attendance workflows are not part of the current public service.</p>
  <p className={styles.notice}>For general enquiries, contact <a href="mailto:contact@anvapublishing.com">contact@anvapublishing.com</a>. For scientific or editorial correspondence, use <a href="mailto:editorial@anvapublishing.com">editorial@anvapublishing.com</a>.</p>
</div></>; }
