import { requireManager } from "@/lib/auth";
import { db } from "@/lib/db";
import { ActionForm } from "@/components/workspace/action-form";
import { createCategoryAction, createPriceAction, issueInvoiceAction, issueReceiptAction } from "@/app/actions/phase3-admin";

export default async function ManageRegistrations({ searchParams }: { searchParams: Promise<{ conferenceId?: string; q?: string }> }) {
  const user = await requireManager(); const params = await searchParams; const q = params.q?.trim(); const assigned = user.role === "ADMINISTRATOR" ? undefined : { some: { userId: user.id, active: true } };
  const conferences = await db.conference.findMany({ where: assigned ? { managerAssignments: assigned } : undefined, select: { id: true, title: true }, orderBy: { title: "asc" } }); const conferenceId = params.conferenceId && conferences.some(c => c.id === params.conferenceId) ? params.conferenceId : undefined;
  const registrations = await db.registration.findMany({ where: { ...(conferenceId ? { conferenceId } : {}), ...(q ? { OR: [{ referenceNumber: { contains: q } }, { user: { name: { contains: q } } }, { user: { email: { contains: q } } }] } : {}) }, include: { user: true, conference: true, category: true, receipts: true, invoices: true }, orderBy: { createdAt: "desc" }, take: 200 });
  return <><header className="admin-header"><div><p className="eyebrow">Operations</p><h1>Registrations & finance</h1></div></header><section className="admin-panel"><form className="filters" method="get"><label>Conference<select name="conferenceId" defaultValue={conferenceId || ""}><option value="">All assigned conferences</option>{conferences.map(c => <option key={c.id} value={c.id}>{c.title}</option>)}</select></label><label>Search<input name="q" defaultValue={q || ""} placeholder="Reference, participant or email" /></label><button>Filter</button></form>{registrations.length ? <div className="responsive-table"><table><thead><tr><th>Reference</th><th>Participant</th><th>Conference/category</th><th>Status</th><th>Amount</th><th>Documents</th></tr></thead><tbody>{registrations.map(r => <tr key={r.id}><td><strong>{r.referenceNumber}</strong></td><td>{r.user.name || r.user.email}<small>{r.user.email}</small></td><td>{r.conference.title}<small>{r.category.name}</small></td><td>{r.status}<small>{r.paymentStatus}</small></td><td>{r.totalAmount.toString()} {r.priceCurrency}</td><td>{r.receipts.length ? "Receipt" : "—"} {r.invoices.length ? "Invoice" : ""}<div className="inline-form"><ActionForm action={issueReceiptAction} submitLabel="Issue receipt" className="inline-form"><input type="hidden" name="conferenceId" value={r.conferenceId}/><input type="hidden" name="registrationId" value={r.id}/></ActionForm><ActionForm action={issueInvoiceAction} submitLabel="Issue invoice" className="inline-form"><input type="hidden" name="conferenceId" value={r.conferenceId}/><input type="hidden" name="registrationId" value={r.id}/></ActionForm></div></td></tr>)}</tbody></table></div> : <p className="empty-state">No registrations have been received yet.</p>}</section>{conferenceId && <section className="admin-panel grid2"><ActionForm action={createCategoryAction} submitLabel="Create category"><input type="hidden" name="conferenceId" value={conferenceId}/><label>Name<input name="name" required/></label><label>Description<textarea name="description"/></label><label>Capacity<input name="capacity" type="number" min="0"/></label><label><input name="requiresAcceptedSubmission" type="checkbox"/> Accepted submission required</label></ActionForm><ActionForm action={createPriceAction} submitLabel="Create price"><label>Category<select name="categoryId" required>{(await db.registrationCategory.findMany({ where: { conferenceId, active: true } })).map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Tier<input name="tier" defaultValue="REGULAR"/></label><label>Amount<input name="amount" type="number" min="0" step="0.01" required/></label><label>Currency<input name="currency" defaultValue="INR"/></label><label>Scope<select name="domestic"><option value="global">Global</option><option value="domestic">Domestic</option><option value="international">International</option></select></label></ActionForm></section>}</>;
}
