import Link from "next/link";
import { requireManager } from "@/lib/auth";
import { db } from "@/lib/db";

const statuses = ["TECHNICAL_CHECK", "RETURNED_FOR_CORRECTION", "UNDER_REVIEW", "REVISION_REQUESTED", "REVISED", "ACCEPTED", "REJECTED", "WITHDRAWN"] as const;
const kinds = ["ABSTRACT", "FULL_PAPER", "POSTER", "WORKSHOP_PROPOSAL", "OTHER"] as const;

export default async function ManagePage({ searchParams }: { searchParams: Promise<{ q?: string; status?: string; conferenceId?: string; kind?: string }> }) {
  const manager = await requireManager(); const query = await searchParams; const q = query.q?.trim();
  const assigned = manager.role === "ADMINISTRATOR" ? null : (await db.conferenceManagerAssignment.findMany({ where: { userId: manager.id, active: true }, select: { conferenceId: true } })).map(x => x.conferenceId);
  const status = statuses.includes(query.status as typeof statuses[number]) ? query.status as typeof statuses[number] : undefined;
  const kind = kinds.includes(query.kind as typeof kinds[number]) ? query.kind as typeof kinds[number] : undefined;
  const submissions = await db.submission.findMany({ where: { status: status || { not: "DRAFT" }, ...(assigned ? { conferenceId: query.conferenceId && assigned.includes(query.conferenceId) ? query.conferenceId : { in: assigned } } : {}), ...(kind ? { kind } : {}), ...(query.conferenceId && !assigned ? { conferenceId: query.conferenceId } : {}), ...(q ? { OR: [{ referenceNumber: { contains: q } }, { title: { contains: q } }, { owner: { email: { contains: q } } }, { owner: { name: { contains: q } } }] } : {}) }, include: { conference: { select: { id: true, title: true } }, owner: { select: { name: true, email: true } }, assignments: { select: { status: true } } }, orderBy: { submittedAt: "desc" } });
  const conferences = await db.conference.findMany({ where: { ...(assigned ? { id: { in: assigned } } : {}), submissions: { some: { status: { not: "DRAFT" } } } }, select: { id: true, title: true }, orderBy: { title: "asc" } });
  return <><header className="admin-header"><div><p className="eyebrow">Editorial management</p><h1>Submissions</h1></div></header><section className="admin-panel"><form className="filters" method="get"><label>Search<input name="q" defaultValue={q || ""} placeholder="Reference, title, or author"/></label><label>Status<select name="status" defaultValue={status || ""}><option value="">All statuses</option>{statuses.map(x => <option key={x}>{x}</option>)}</select></label><label>Type<select name="kind" defaultValue={kind || ""}><option value="">All types</option>{kinds.map(x => <option key={x}>{x}</option>)}</select></label><label>Conference<select name="conferenceId" defaultValue={query.conferenceId || ""}><option value="">All conferences</option>{conferences.map(c => <option value={c.id} key={c.id}>{c.title}</option>)}</select></label><button>Filter</button></form><div className="responsive-table"><table><thead><tr><th>Reference / submission</th><th>Conference</th><th>Author</th><th>Status</th><th>Reviews</th></tr></thead><tbody>{submissions.map(s => <tr key={s.id}><td><Link href={`/workspace/manage/submissions/${s.id}`}><strong>{s.referenceNumber}</strong><small>{s.title}</small></Link></td><td>{s.conference.title}</td><td>{s.owner.name || s.owner.email}</td><td>{s.status.replaceAll("_", " ")}</td><td>{s.assignments.filter(a => a.status === "COMPLETED").length}/{s.assignments.length}</td></tr>)}</tbody></table></div>{!submissions.length && <div className="empty-state">No submissions match these filters.</div>}</section></>;
}
