import { createSubmissionAction } from "@/app/actions/submissions";
import { ActionForm } from "@/components/workspace/action-form";
import { requireAccount } from "@/lib/auth";
import { db } from "@/lib/db";

export default async function NewSubmissionPage() {
  await requireAccount();
  const conferences = await db.conference.findMany({ where: { status: { in: ["PUBLISHED", "ONGOING"] }, submissionState: "OPEN", OR: [{ abstractAllowed: true }, { fullPaperAllowed: true }, { posterAllowed: true }, { workshopProposalAllowed: true }] }, include: { tracks: true }, orderBy: { startDate: "asc" } });
  return <><header className="admin-header"><div><p className="eyebrow">Author workspace</p><h1>New submission</h1></div></header><section className="admin-panel">{conferences.length ? <ActionForm action={createSubmissionAction} submitLabel="Create draft"><fieldset><legend>Submission details</legend><label className="wide">Conference<select name="conferenceId" required defaultValue=""><option value="" disabled>Select a conference</option>{conferences.map(c => <option value={c.id} key={c.id}>{c.title}</option>)}</select></label><label className="wide">Title<input name="title" required minLength={5} maxLength={250}/></label><label>Type<select name="kind"><option value="ABSTRACT">Abstract</option><option value="FULL_PAPER">Full paper</option><option value="POSTER">Poster</option><option value="WORKSHOP_PROPOSAL">Workshop proposal</option></select></label><label>Track (optional)<select name="trackId"><option value="">No track selected</option>{conferences.flatMap(c => c.tracks.map(t => <option value={t.id} key={t.id}>{c.acronym || c.title}: {t.title}</option>))}</select></label><label className="wide">Abstract or summary<textarea name="abstractText" required minLength={50} maxLength={10000} rows={10}/></label><label className="wide">Keywords<input name="keywords" maxLength={500} placeholder="Comma-separated"/></label></fieldset></ActionForm> : <div className="empty-state"><h2>No open calls</h2><p>There are currently no published conferences accepting submissions.</p></div>}</section></>;
}
