"use server";
import { createHash, randomBytes } from "node:crypto";
import { revalidatePath } from "next/cache";
import { db } from "@/lib/db";
import { requireConferenceManager } from "@/lib/auth";
import { audit } from "@/lib/audit";
import type { ActionState } from "@/lib/validation";
export async function generateAttendeeAction(_: ActionState, fd: FormData): Promise<ActionState> { const c = String(fd.get("conferenceId") || ""); const u = await requireConferenceManager(c); const registrationId = String(fd.get("registrationId") || ""); const r = await db.registration.findFirst({ where: { id: registrationId, conferenceId: c, OR: [{ status: "CONFIRMED" }, { status: "COMPLIMENTARY" }] }, include: { user: true, category: true } }); if (!r) return { ok: false, message: "Only confirmed registrations can become attendees." }; const token = randomBytes(32).toString("base64url"); await db.attendee.upsert({ where: { registrationId }, update: { status: "ACTIVE" }, create: { conferenceId: c, registrationId, displayName: r.user.name || r.user.email, affiliation: r.user.affiliation, attendeeType: r.category.name, presenter: r.presenter, qrTokenHash: createHash("sha256").update(token).digest("hex") } }); await audit("ATTENDEE_GENERATED", u.id, "Registration", registrationId); revalidatePath("/workspace/manage/attendees"); return { ok: true, message: "Attendee record is ready." }; }
export async function checkInAction(_: ActionState, fd: FormData): Promise<ActionState> { const c = String(fd.get("conferenceId") || ""); const u = await requireConferenceManager(c); const attendeeId = String(fd.get("attendeeId") || ""); const a = await db.attendee.findFirst({ where: { id: attendeeId, conferenceId: c, status: "ACTIVE" }, include: { checkIns: true } }); if (!a) return { ok: false, message: "Attendee not found or inactive." }; if (a.checkIns.length) return { ok: true, message: "Attendee was already checked in." }; await db.checkIn.create({ data: { attendeeId, recordedById: u.id, method: "MANUAL" } }); await audit("ATTENDEE_CHECKED_IN", u.id, "Attendee", attendeeId); revalidatePath("/workspace/manage/attendees"); return { ok: true, message: "Checked in successfully." }; }
export async function recordAttendanceAction(_: ActionState, fd: FormData): Promise<ActionState> { const c = String(fd.get("conferenceId") || ""); const u = await requireConferenceManager(c); const attendeeId = String(fd.get("attendeeId") || ""); const a = await db.attendee.findFirst({ where: { id: attendeeId, conferenceId: c, status: "ACTIVE" } }); if (!a) return { ok: false, message: "Attendee not found." }; await db.attendanceRecord.create({ data: { attendeeId, recordedById: u.id, method: "MANUAL", sessionId: String(fd.get("sessionId") || "") || undefined } }); await audit("ATTENDANCE_RECORDED", u.id, "Attendee", attendeeId); return { ok: true, message: "Attendance recorded." }; }
