"use server";
import { randomBytes } from "node:crypto";
import { revalidatePath } from "next/cache";
import { db } from "@/lib/db";
import { requireAdmin, requireConferenceManager } from "@/lib/auth";
import { audit } from "@/lib/audit";
import type { ActionState } from "@/lib/validation";
import type { WaiverType, RefundStatus, DiscountType } from "@prisma/client";

const text = (v: FormDataEntryValue | null) => String(v || "").trim();
const ref = (p: string) => `${p}-${new Date().getFullYear()}-${randomBytes(5).toString("hex").toUpperCase()}`;

export async function createCategoryAction(_: ActionState, fd: FormData): Promise<ActionState> { const c = text(fd.get("conferenceId")); const u = await requireConferenceManager(c); const name = text(fd.get("name")); if (!name) return { ok: false, message: "Category name is required." }; await db.registrationCategory.create({ data: { conferenceId: c, name, description: text(fd.get("description")) || undefined, capacity: Number(fd.get("capacity") || 0) || undefined, requiresAcceptedSubmission: fd.get("requiresAcceptedSubmission") === "on", waitlistEnabled: fd.get("waitlistEnabled") === "on" } }); await audit("REGISTRATION_CATEGORY_CREATED", u.id, "Conference", c); revalidatePath("/workspace/manage/registrations"); return { ok: true, message: "Category created." }; }
export async function createPriceAction(_: ActionState, fd: FormData): Promise<ActionState> { const categoryId = text(fd.get("categoryId")); const cat = await db.registrationCategory.findUnique({ where: { id: categoryId } }); if (!cat) return { ok: false, message: "Category not found." }; const u = await requireConferenceManager(cat.conferenceId); const amount = Number(fd.get("amount")); if (!Number.isFinite(amount) || amount < 0) return { ok: false, message: "Enter a valid amount." }; await db.registrationPrice.create({ data: { categoryId, tier: text(fd.get("tier")) || "REGULAR", amount, currency: text(fd.get("currency")).toUpperCase() || "INR", domestic: fd.get("domestic") === "global" ? null : fd.get("domestic") === "domestic" } }); await audit("REGISTRATION_PRICE_CREATED", u.id, "RegistrationCategory", categoryId); return { ok: true, message: "Price created." }; }
export async function createDiscountAction(_: ActionState, fd: FormData): Promise<ActionState> { const c=text(fd.get("conferenceId")); const u=await requireConferenceManager(c); const code=text(fd.get("code")).toUpperCase(); const value=Number(fd.get("value")); if(!code||!Number.isFinite(value)||value<0)return{ok:false,message:"Enter a valid discount."}; await db.discountCode.create({data:{conferenceId:c,code,description:text(fd.get("description"))||undefined,type:(text(fd.get("type"))||"FIXED") as DiscountType,value,active:true}}); await audit("DISCOUNT_CREATED",u.id,"Conference",c,{code}); return{ok:true,message:"Discount created."}; }
export async function assignManagerAction(_: ActionState, fd: FormData): Promise<ActionState> { const admin = await requireAdmin(); const conferenceId = text(fd.get("conferenceId")); const userId = text(fd.get("userId")); if (!conferenceId || !userId) return { ok: false, message: "Select a conference and manager." }; await db.conferenceManagerAssignment.upsert({ where: { conferenceId_userId: { conferenceId, userId } }, update: { active: true }, create: { conferenceId, userId } }); await audit("MANAGER_ASSIGNED", admin.id, "Conference", conferenceId, { userId }); revalidatePath("/admin/users"); return { ok: true, message: "Manager assignment saved." }; }
export async function removeManagerAction(_: ActionState, fd: FormData): Promise<ActionState> { const admin = await requireAdmin(); const conferenceId = text(fd.get("conferenceId")); const userId = text(fd.get("userId")); await db.conferenceManagerAssignment.updateMany({ where: { conferenceId, userId }, data: { active: false } }); await audit("MANAGER_REMOVED", admin.id, "Conference", conferenceId, { userId }); revalidatePath("/admin/users"); return { ok: true, message: "Manager assignment removed." }; }
export async function issueReceiptAction(_: ActionState, fd: FormData): Promise<ActionState> { const c = text(fd.get("conferenceId")); const u = await requireConferenceManager(c); const id = text(fd.get("registrationId")); const r = await db.registration.findFirst({ where: { id, conferenceId: c }, include: { receipts: true } }); if (!r || (r.paymentStatus !== "PAID" && r.status !== "COMPLIMENTARY")) return { ok: false, message: "A verified payment or complimentary registration is required." }; if (r.receipts.length) return { ok: true, message: "Receipt already issued." }; await db.receipt.create({ data: { receiptNumber: ref("ANVA-RCP"), registrationId: r.id, userId: r.userId, conferenceId: c, amount: r.priceAmount, discount: r.discountAmount, tax: r.taxAmount, total: r.totalAmount, currency: r.priceCurrency, paymentMethod: r.paymentStatus === "PAID" ? "manual" : "complimentary" } }); await audit("RECEIPT_ISSUED", u.id, "Registration", id); return { ok: true, message: "Receipt issued." }; }
export async function issueInvoiceAction(_: ActionState, fd: FormData): Promise<ActionState> { const c = text(fd.get("conferenceId")); const u = await requireConferenceManager(c); const id = text(fd.get("registrationId")); const r = await db.registration.findFirst({ where: { id, conferenceId: c }, include: { invoices: true, category: true } }); if (!r) return { ok: false, message: "Registration not found." }; if (r.invoices.length) return { ok: true, message: "Invoice already issued." }; await db.invoice.create({ data: { invoiceNumber: ref("ANVA-INV"), registrationId: r.id, userId: r.userId, billingName: r.billingName || "Participant", billingAddress: r.billingAddress, taxId: r.billingTaxId, subtotal: r.priceAmount, discount: r.discountAmount, tax: r.taxAmount, total: r.totalAmount, currency: r.priceCurrency, conferenceId: c, lines: { create: { description: r.category.name, quantity: 1, unitAmount: r.priceAmount, amount: r.priceAmount } } } }); await audit("INVOICE_ISSUED", u.id, "Registration", id); return { ok: true, message: "Invoice issued." }; }

export async function requestCancellationAction(_: ActionState, fd: FormData): Promise<ActionState> { const { requireAccount } = await import("@/lib/auth"); const u = await requireAccount(); const id = text(fd.get("registrationId")); const r = await db.registration.findFirst({ where: { id, userId: u.id }, select: { id: true } }); if (!r) return { ok: false, message: "Registration not found." }; await db.cancellationRequest.create({ data: { registrationId: id, reason: text(fd.get("reason")) || "Participant requested cancellation." } }); await audit("CANCELLATION_REQUESTED", u.id, "Registration", id); return { ok: true, message: "Cancellation request submitted." }; }
export async function processCancellationAction(_: ActionState, fd: FormData): Promise<ActionState> { const c = text(fd.get("conferenceId")); const u = await requireConferenceManager(c); const id = text(fd.get("requestId")); const approve = text(fd.get("decision")) === "APPROVE"; const req = await db.cancellationRequest.findUnique({ where: { id }, include: { registration: true } }); if (!req || req.registration.conferenceId !== c) return { ok: false, message: "Cancellation request not found." }; await db.cancellationRequest.update({ where: { id }, data: { status: approve ? "APPROVED" : "REJECTED", decidedById: u.id, decidedAt: new Date(), notes: text(fd.get("notes")) || undefined } }); if (approve) await db.registration.update({ where: { id: req.registrationId }, data: { status: "CANCELLED" } }); await audit("CANCELLATION_PROCESSED", u.id, "CancellationRequest", id); return { ok: true, message: approve ? "Cancellation approved." : "Cancellation rejected." }; }
export async function grantWaiverAction(_: ActionState, fd: FormData): Promise<ActionState> { const c = text(fd.get("conferenceId")); const u = await requireConferenceManager(c); const id = text(fd.get("registrationId")); const r = await db.registration.findFirst({ where: { id, conferenceId: c } }); if (!r) return { ok: false, message: "Registration not found." }; const amount = Number(fd.get("amount") || 0); if (!Number.isFinite(amount) || amount < 0 || amount > Number(r.priceAmount)) return { ok: false, message: "Waiver amount is invalid." }; const type = text(fd.get("type")) || "PARTIAL"; await db.registrationWaiver.create({ data: { registrationId: id, type: type as WaiverType, reason: text(fd.get("reason")) || "Administrative waiver", amount, authorizedById: u.id } }); const total = Math.max(0, Number(r.totalAmount) - amount); await db.registration.update({ where: { id }, data: { waiverAmount: { increment: amount }, totalAmount: total, status: total === 0 ? "COMPLIMENTARY" : r.status, paymentStatus: total === 0 ? "NOT_REQUIRED" : r.paymentStatus } }); await audit("WAIVER_GRANTED", u.id, "Registration", id); return { ok: true, message: "Waiver granted." }; }
export async function requestRefundAction(_: ActionState, fd: FormData): Promise<ActionState> { const c = text(fd.get("conferenceId")); const u = await requireConferenceManager(c); const id = text(fd.get("registrationId")); const r = await db.registration.findFirst({ where: { id, conferenceId: c }, include: { payments: true, refunds: true } }); if (!r) return { ok: false, message: "Registration not found." }; const amount = Number(fd.get("amount") || 0); const paid = r.payments.filter(p => p.status === "PAID").reduce((n, p) => n + Number(p.amount), 0); const refunded = r.refunds.filter(x => ["REQUESTED","APPROVED","PROCESSING","COMPLETED"].includes(x.status)).reduce((n, x) => n + Number(x.amount), 0); if (!Number.isFinite(amount) || amount <= 0 || amount + refunded > paid) return { ok: false, message: "Refund exceeds the verified paid amount." }; await db.refund.create({ data: { registrationId: id, amount, currency: r.priceCurrency, reason: text(fd.get("reason")) || "Refund requested", requestedById: u.id, paymentId: r.payments.find(p => p.status === "PAID")?.id } }); await audit("REFUND_REQUESTED", u.id, "Registration", id); return { ok: true, message: "Refund request recorded." }; }
export async function processRefundAction(_: ActionState, fd: FormData): Promise<ActionState> { const c = text(fd.get("conferenceId")); const u = await requireConferenceManager(c); const id = text(fd.get("refundId")); const status = text(fd.get("status")); const r = await db.refund.findUnique({ where: { id }, include: { registration: true } }); if (!r || r.registration.conferenceId !== c || !["APPROVED","PROCESSING","COMPLETED","REJECTED"].includes(status)) return { ok: false, message: "Refund not found or invalid status." }; await db.refund.update({ where: { id }, data: { status: status as RefundStatus, approvedById: u.id, approvedAt: new Date(), completedAt: status === "COMPLETED" ? new Date() : undefined, providerReference: text(fd.get("reference")) || undefined } }); if (status === "COMPLETED") await db.registration.update({ where: { id: r.registrationId }, data: { paymentStatus: "REFUNDED", status: "REFUNDED" } }); await audit("REFUND_STATUS_CHANGED", u.id, "Refund", id); return { ok: true, message: "Refund status updated." }; }
