"use server";
import { randomBytes } from "node:crypto";
import { revalidatePath } from "next/cache";
import { db } from "@/lib/db";
import { requireAdmin, requireConferenceManager } from "@/lib/auth";
import { audit } from "@/lib/audit";
import type { ActionState } from "@/lib/validation";

const text = (v: FormDataEntryValue | null) => String(v || "").trim();
const ref = (p: string) => `${p}-${new Date().getFullYear()}-${randomBytes(5).toString("hex").toUpperCase()}`;

export async function createCategoryAction(_: ActionState, fd: FormData): Promise<ActionState> { const c = text(fd.get("conferenceId")); const u = await requireConferenceManager(c); const name = text(fd.get("name")); if (!name) return { ok: false, message: "Category name is required." }; await db.registrationCategory.create({ data: { conferenceId: c, name, description: text(fd.get("description")) || undefined, capacity: Number(fd.get("capacity") || 0) || undefined, requiresAcceptedSubmission: fd.get("requiresAcceptedSubmission") === "on", waitlistEnabled: fd.get("waitlistEnabled") === "on" } }); await audit("REGISTRATION_CATEGORY_CREATED", u.id, "Conference", c); revalidatePath("/workspace/manage/registrations"); return { ok: true, message: "Category created." }; }
export async function createPriceAction(_: ActionState, fd: FormData): Promise<ActionState> { const categoryId = text(fd.get("categoryId")); const cat = await db.registrationCategory.findUnique({ where: { id: categoryId } }); if (!cat) return { ok: false, message: "Category not found." }; const u = await requireConferenceManager(cat.conferenceId); const amount = Number(fd.get("amount")); if (!Number.isFinite(amount) || amount < 0) return { ok: false, message: "Enter a valid amount." }; await db.registrationPrice.create({ data: { categoryId, tier: text(fd.get("tier")) || "REGULAR", amount, currency: text(fd.get("currency")).toUpperCase() || "INR", domestic: fd.get("domestic") === "global" ? null : fd.get("domestic") === "domestic" } }); await audit("REGISTRATION_PRICE_CREATED", u.id, "RegistrationCategory", categoryId); return { ok: true, message: "Price created." }; }
export async function assignManagerAction(_: ActionState, fd: FormData): Promise<ActionState> { const admin = await requireAdmin(); const conferenceId = text(fd.get("conferenceId")); const userId = text(fd.get("userId")); if (!conferenceId || !userId) return { ok: false, message: "Select a conference and manager." }; await db.conferenceManagerAssignment.upsert({ where: { conferenceId_userId: { conferenceId, userId } }, update: { active: true }, create: { conferenceId, userId } }); await audit("MANAGER_ASSIGNED", admin.id, "Conference", conferenceId, { userId }); revalidatePath("/admin/users"); return { ok: true, message: "Manager assignment saved." }; }
export async function removeManagerAction(_: ActionState, fd: FormData): Promise<ActionState> { const admin = await requireAdmin(); const conferenceId = text(fd.get("conferenceId")); const userId = text(fd.get("userId")); await db.conferenceManagerAssignment.updateMany({ where: { conferenceId, userId }, data: { active: false } }); await audit("MANAGER_REMOVED", admin.id, "Conference", conferenceId, { userId }); revalidatePath("/admin/users"); return { ok: true, message: "Manager assignment removed." }; }
export async function issueReceiptAction(_: ActionState, fd: FormData): Promise<ActionState> { const c = text(fd.get("conferenceId")); const u = await requireConferenceManager(c); const id = text(fd.get("registrationId")); const r = await db.registration.findFirst({ where: { id, conferenceId: c }, include: { receipts: true } }); if (!r || (r.paymentStatus !== "PAID" && r.status !== "COMPLIMENTARY")) return { ok: false, message: "A verified payment or complimentary registration is required." }; if (r.receipts.length) return { ok: true, message: "Receipt already issued." }; await db.receipt.create({ data: { receiptNumber: ref("ANVA-RCP"), registrationId: r.id, userId: r.userId, conferenceId: c, amount: r.priceAmount, discount: r.discountAmount, tax: r.taxAmount, total: r.totalAmount, currency: r.priceCurrency, paymentMethod: r.paymentStatus === "PAID" ? "manual" : "complimentary" } }); await audit("RECEIPT_ISSUED", u.id, "Registration", id); return { ok: true, message: "Receipt issued." }; }
export async function issueInvoiceAction(_: ActionState, fd: FormData): Promise<ActionState> { const c = text(fd.get("conferenceId")); const u = await requireConferenceManager(c); const id = text(fd.get("registrationId")); const r = await db.registration.findFirst({ where: { id, conferenceId: c }, include: { invoices: true, category: true } }); if (!r) return { ok: false, message: "Registration not found." }; if (r.invoices.length) return { ok: true, message: "Invoice already issued." }; await db.invoice.create({ data: { invoiceNumber: ref("ANVA-INV"), registrationId: r.id, userId: r.userId, billingName: r.billingName || "Participant", billingAddress: r.billingAddress, taxId: r.billingTaxId, subtotal: r.priceAmount, discount: r.discountAmount, tax: r.taxAmount, total: r.totalAmount, currency: r.priceCurrency, conferenceId: c, lines: { create: { description: r.category.name, quantity: 1, unitAmount: r.priceAmount, amount: r.priceAmount } } } }); await audit("INVOICE_ISSUED", u.id, "Registration", id); return { ok: true, message: "Invoice issued." }; }
